### ISSUE TITLE
Move to `chalk` organization.

### ISSUE THREAD

**Issue by dthree** [chalk/slice-ansi#1]
@Qix- @sindresorhus

I needed to make another ANSI library - this does the equivalent of a native `array.slice()` in JS, however, it safely handles ANSI escape codes so you don't slice half-way into an escape code or have the wrong length on your slice due to hidden characters.

I'd like to move this repo into the `chalk` organization, which seems like a better home for it.

This okay with you guys?

**Comment by Qix-** [comment]
Totally up to @sindresorhus and @jbnicolai. :)

**Comment by sindresorhus** [comment]
Yes :) Just move the repo to me and I'll move it into the org.

**Comment by dthree** [comment]
Done :)

**Comment by sindresorhus** [comment]
Thanks @dthree. Welcome to the `chalk` org :)

**Comment by dthree** [comment]
Thanks!! :D
