### ISSUE TITLE
Lose characters when fullwidth characters exist and end is not specified

### ISSUE THREAD

**Issue by bet4it** [chalk/slice-ansi#26]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/chalk/slice-ansi/issues/26)

Lose characters when there are fullwidth characters in the string and the third argument `end` is not specified:
```javascript
const str = sliceAnsi("古古test", 0);
// => '古古te'
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Submitted pull Requests
- [#29 supports fullwidth characters & not specified end](https://issuehunt.io/r/chalk/slice-ansi/pull/29)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/slice-ansi/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
I've added a failing test for this: https://github.com/chalk/slice-ansi/commit/108d0ad176da3bb797fb3037e9a838c5c00eba84
