### ISSUE TITLE
yarn can't find ^5.0.0

### ISSUE THREAD

**Issue by jiheapark** [chalk/slice-ansi#36]
I tried `yarn add lint-staged` to dev in my project.
But this is what I got
<img width="824" alt="스크린샷 2022-02-18 오전 10 10 47" src="https://user-images.githubusercontent.com/26865541/154598808-d0eda568-c4d0-4cfb-b6e9-4402d8ca5c5d.png">

So I tried add slice-ansi in package.json.
But I got this...
<img width="739" alt="스크린샷 2022-02-18 오전 10 11 18" src="https://user-images.githubusercontent.com/26865541/154598814-353f1dbf-eac1-4ec9-b7f8-f46bf2df1090.png">

what should I do??
Why I can't find 5.0.0 version of slice-ansi??

**Comment by sindresorhus** [comment]
This is not the place to ask for Yarn support.

---

```
❯ npm info slice-ansi versions
[
  '0.0.2', '0.0.3',
  '0.0.4', '0.1.0',
  '1.0.0', '2.0.0',
  '2.1.0', '3.0.0',
  '4.0.0', '5.0.0'
]
```
