### ISSUE TITLE
Support for unicode surrogate pairs

### ISSUE THREAD

**Issue by sindresorhus** [chalk/slice-ansi#5]
https://mathiasbynens.be/notes/javascript-unicode

I've added a failing skipped test: https://github.com/chalk/slice-ansi/commit/fab456095107f514031f7ae73ced26249d6c9691
## 

Same as https://github.com/chalk/wrap-ansi/issues/11.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/kevva/slice-ansi/commit/ea51863ce7272e7c0dfd74caf0f20525cf6b6fa0

**Comment by slammayjammay** [comment]
It seems to think surrogate pair character width is 1. For example this string `🎂🎂🎂🎂` has a width of 8, but slicing from 0 to 4 returns the entire string.

```js
const string = '🎂🎂🎂🎂';
sliceAnsi(string, 0, 4); // => '🎂🎂🎂🎂'
sliceAnsi(string, 0, 2); // => '🎂🎂'
```

I would have expected this:

```js
const string = '🎂🎂🎂🎂';
sliceAnsi(string, 0, 4); // => '🎂🎂'
sliceAnsi(string, 0, 2); // => '🎂'
sliceAnsi(string, 0, 8); // => '🎂🎂🎂🎂'
```

**Comment by slammayjammay** [comment]
Can this be re-opened?
